### ISSUE TITLE
self hosted supabase/postgres connection timeout

### ISSUE THREAD

**Issue by rajan-personal** [motor-admin/motor-admin#111]
I am able to connect to the database via the local motor-admin, but I am getting a connection timeout error when I try to connect to the server motor-admin.

There is no proxy or special authentication in place.

Any ideas on what could be causing this?

```
E, [2023-08-15T18:23:47.111608 #1] ERROR -- : [9b933749-e0aa-4bdc-9d62-e2c414fd9643] /usr/local/bundle/gems/pg-1.4.5/lib/pg/connection.rb:632:in `async_connect_or_reset'
/usr/local/bundle/gems/pg-1.4.5/lib/pg/connection.rb:760:in `connect_to_hosts'
/usr/local/bundle/gems/pg-1.4.5/lib/pg/connection.rb:695:in `new'
/usr/local/bundle/gems/pg-1.4.5/lib/pg.rb:69:in `connect'
/opt/motor-admin/app/controllers/api/verify_db_connection_controller.rb:19:in `verify_db_connection!'
/opt/motor-admin/app/controllers/api/verify_db_connection_controller.rb:10:in `create'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/base.rb:215:in `process_action'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/rendering.rb:53:in `process_action'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/bundle/gems/audited-5.3.2/lib/audited/sweeper.rb:16:in `around'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/bundle/gems/audited-5.3.2/lib/audited/sweeper.rb:16:in `around'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/callbacks.rb:233:in `process_action'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `instrument'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
/usr/local/bundle/gems/activerecord-7.0.4.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/base.rb:151:in `process'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal.rb:188:in `dispatch'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal.rb:251:in `dispatch'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `each'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/etag.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/conditional_get.rb:40:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/cookies.rb:704:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:99:in `run_callbacks'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
/usr/local/bundle/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
/usr/local/bundle/gems/railties-7.0.4.3/lib/rails/rack/logger.rb:25:in `block in call'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/bundle/gems/railties-7.0.4.3/lib/rails/rack/logger.rb:25:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/method_override.rb:24:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/static.rb:23:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/sendfile.rb:110:in `call'
/usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
/usr/local/bundle/gems/railties-7.0.4.3/lib/rails/engine.rb:530:in `call'
/usr/local/bundle/gems/puma-6.0.1/lib/puma/configuration.rb:268:in `call'
/usr/local/bundle/gems/puma-6.0.1/lib/puma/request.rb:93:in `block in handle_request'
/usr/local/bundle/gems/puma-6.0.1/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/usr/local/bundle/gems/puma-6.0.1/lib/puma/request.rb:92:in `handle_request'
/usr/local/bundle/gems/puma-6.0.1/lib/puma/server.rb:429:in `process_client'
/usr/local/bundle/gems/puma-6.0.1/lib/puma/server.rb:232:in `block in run'
/usr/local/bundle/gems/puma-6.0.1/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
I, [2023-08-15T18:23:47.112280 #1]  INFO -- : [9b933749-e0aa-4bdc-9d62-e2c414fd9643] {"method":"POST","path":"/api/verify_db_connection","status":500,"duration":129460.9,"view":0.27,"db":0.32,"fwd":"49.47.71.127","uid":1}
```

**Comment by omohokcoj** [comment]
@rajan-personal looks like the error is related to your server env if connecting to the DB from local motor-admin works.
Make sure your server is able to connect to the specific supabase db port.
