### ISSUE TITLE
Error when creating association

### ISSUE THREAD

**Issue by bombillazo** [motor-admin/motor-admin#116]
Hello, we are getting the following error when creating some of our associations:

```bash
dashboard-app-1       | I, [2023-09-21T23:59:13.436532 #1]  INFO -- : [89756e51-7395-49e0-9036-c0f2dffc96f6] {"method":"GET","path":"/api/data/businesses/63e2bad7-d4f6-4733-a3ed-8c8b248ce54b/memberships","status":200,"duration":20.71,"view":0.11,"db":9.84,"fwd":"192.168.65.1","uid":1}
dashboard-app-1       | E, [2023-09-21T23:59:13.440085 #1] ERROR -- : [e46915e5-9046-4885-88e8-27e35a595a46] undefined method `user' for #<Member id: "6b1eac10-dc65-4370-afa3-06bf7388823f", role: "owner", user_id: "27d98873-0074-40ea-8ec0-8d23dbadbeb8", business_id: "63e2bad7-d4f6-4733-a3ed-8c8b248ce54b", metadata: {"type"=>"owner", "title"=>"owner", "ownership_percentage"=>100}, created_at: "2023-09-20 13:00:08.056076000 +0000">
dashboard-app-1       | E, [2023-09-21T23:59:13.441562 #1] ERROR -- : [e46915e5-9046-4885-88e8-27e35a595a46] /usr/local/bundle/gems/activemodel-7.0.4.3/lib/active_model/attribute_methods.rb:458:in `method_missing'
dashboard-app-1       | /usr/local/bundle/gems/activemodel-7.0.4.3/lib/active_model/serialization.rb:192:in `block in serializable_add_includes'
dashboard-app-1       | /usr/local/bundle/gems/activemodel-7.0.4.3/lib/active_model/serialization.rb:191:in `each'
dashboard-app-1       | /usr/local/bundle/gems/activemodel-7.0.4.3/lib/active_model/serialization.rb:191:in `serializable_add_includes'
dashboard-app-1       | /usr/local/bundle/gems/activemodel-7.0.4.3/lib/active_model/serialization.rb:140:in `serializable_hash'
dashboard-app-1       | /usr/local/bundle/gems/activerecord-7.0.4.3/lib/active_record/serialization.rb:21:in `serializable_hash'
dashboard-app-1       | /usr/local/bundle/gems/activemodel-7.0.4.3/lib/active_model/serializers/json.rb:103:in `as_json'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/core_ext/object/json.rb:159:in `map'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/core_ext/object/json.rb:159:in `as_json'
dashboard-app-1       | /usr/local/bundle/gems/activerecord-7.0.4.3/lib/active_record/relation/delegation.rb:88:in `as_json'
dashboard-app-1       | /opt/motor-admin/vendor/motor-admin/lib/motor/api_query/build_json.rb:25:in `call'
dashboard-app-1       | /opt/motor-admin/vendor/motor-admin/app/controllers/motor/data_controller.rb:17:in `index'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/base.rb:215:in `process_action'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/rendering.rb:53:in `process_action'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
dashboard-app-1       | /usr/local/bundle/gems/audited-5.3.2/lib/audited/sweeper.rb:16:in `around'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
dashboard-app-1       | /usr/local/bundle/gems/audited-5.3.2/lib/audited/sweeper.rb:16:in `around'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/callbacks.rb:233:in `process_action'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `block in instrument'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `instrument'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
dashboard-app-1       | /usr/local/bundle/gems/activerecord-7.0.4.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/base.rb:151:in `process'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal.rb:188:in `dispatch'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal.rb:251:in `dispatch'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:32:in `serve'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `each'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `serve'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
dashboard-app-1       | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/engine.rb:530:in `call'
dashboard-app-1       | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/railtie.rb:226:in `public_send'
dashboard-app-1       | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/railtie.rb:226:in `method_missing'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `each'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `serve'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
dashboard-app-1       | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
dashboard-app-1       | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
dashboard-app-1       | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
dashboard-app-1       | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
dashboard-app-1       | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/etag.rb:27:in `call'
dashboard-app-1       | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/conditional_get.rb:27:in `call'
dashboard-app-1       | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/head.rb:12:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
dashboard-app-1       | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:266:in `context'
dashboard-app-1       | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:260:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/cookies.rb:704:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:99:in `run_callbacks'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
dashboard-app-1       | /usr/local/bundle/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
dashboard-app-1       | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/rack/logger.rb:25:in `block in call'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:37:in `tagged'
dashboard-app-1       | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `tagged'
dashboard-app-1       | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/rack/logger.rb:25:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
dashboard-app-1       | /usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
dashboard-app-1       | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/method_override.rb:24:in `call'
dashboard-app-1       | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/runtime.rb:22:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/static.rb:23:in `call'
dashboard-app-1       | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/sendfile.rb:110:in `call'
dashboard-app-1       | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
dashboard-app-1       | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/engine.rb:530:in `call'
dashboard-app-1       | /usr/local/bundle/gems/puma-6.0.1/lib/puma/configuration.rb:268:in `call'
dashboard-app-1       | /usr/local/bundle/gems/puma-6.0.1/lib/puma/request.rb:93:in `block in handle_request'
dashboard-app-1       | /usr/local/bundle/gems/puma-6.0.1/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
dashboard-app-1       | /usr/local/bundle/gems/puma-6.0.1/lib/puma/request.rb:92:in `handle_request'
dashboard-app-1       | /usr/local/bundle/gems/puma-6.0.1/lib/puma/server.rb:429:in `process_client'
dashboard-app-1       | /usr/local/bundle/gems/puma-6.0.1/lib/puma/server.rb:232:in `block in run'
dashboard-app-1       | /usr/local/bundle/gems/puma-6.0.1/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
dashboard-app-1       | I, [2023-09-21T23:59:13.441415 #1]  INFO -- : [45179302-857a-4cdd-b9d7-edf0859cd3ff] {"method":"POST","path":"/api/resources","status":200,"duration":21.07,"view":0.55,"db":9.86,"fwd":"192.168.65.1","uid":1}
dashboard-app-1       | I, [2023-09-21T23:59:13.442575 #1]  INFO -- : [e46915e5-9046-4885-88e8-27e35a595a46] {"method":"GET","path":"/api/data/businesses/63e2bad7-d4f6-4733-a3ed-8c8b248ce54b/memberships","status":500,"duration":22.89,"view":0.14,"db":10.76,"fwd":"192.168.65.1","uid":1}

```

**Comment by bombillazo** [comment]
The issue seems to be related to using parenthesis `()` in the association name at the very least, maybe using paranthesis in any name will also give issues...

**Comment by bombillazo** [comment]
Moved to https://github.com/motor-admin/motor-admin-rails/issues/134
