### ISSUE TITLE
Fails in Rails 7.2 beta

### ISSUE THREAD

**Issue by kg-currenxie** [motor-admin/motor-admin#143]
Installing 0.4.27 and running `rails server`
```
/Users/frexuz/.gem/ruby/3.3.0/gems/activesupport-7.2.0.beta3/lib/active_support/cache.rb:769:in `default_serializer': Unrecognized ActiveSupport::Cache.format_version: 7.2 (ArgumentError)

            raise ArgumentError, "Unrecognized ActiveSupport::Cache.format_version: #{Cache.format_version.inspect}"
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/frexuz/.gem/ruby/3.3.0/gems/activesupport-7.2.0.beta3/lib/active_support/cache.rb:303:in `block in initialize'
	from /Users/frexuz/.gem/ruby/3.3.0/gems/activesupport-7.2.0.beta3/lib/active_support/cache.rb:301:in `delete'
	from /Users/frexuz/.gem/ruby/3.3.0/gems/activesupport-7.2.0.beta3/lib/active_support/cache.rb:301:in `initialize'
	from /Users/frexuz/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/motor-admin-0.4.27/lib/motor/assets.rb:15:in `new'
```

**Comment by scoobyclub** [comment]
I get the same error. I have a feeling this gem is dead. It has been giving out warnings for a while.

**Comment by bendangelo** [comment]
I've opened a PR to fix this: https://github.com/motor-admin/motor-admin-rails/pull/172
