### ISSUE TITLE
Can not login into motor admin

### ISSUE THREAD

**Issue by fachri10xers** [motor-admin/motor-admin#145]
when I try to log in, I get this error, where can I see the motor admin log?
![image](https://github.com/user-attachments/assets/7743b90b-2703-4b16-a4b5-c35852031400)

**Comment by abdul-verteil** [comment]
I am facing the same issue. was this ever resolved?
these are the last few errors:
```log
[06610406-6809-49ca-93b5-170a9f816418] actionpack (7.0.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
[06610406-6809-49ca-93b5-170a9f816418] actionpack (7.0.4.3) lib/action_dispatch/middleware/static.rb:23:in `call'
[06610406-6809-49ca-93b5-170a9f816418] rack (2.2.6.4) lib/rack/sendfile.rb:110:in `call'
[06610406-6809-49ca-93b5-170a9f816418] actionpack (7.0.4.3) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
[06610406-6809-49ca-93b5-170a9f816418] railties (7.0.4.3) lib/rails/engine.rb:530:in `call'
[06610406-6809-49ca-93b5-170a9f816418] puma (6.0.1) lib/puma/configuration.rb:268:in `call'
[06610406-6809-49ca-93b5-170a9f816418] puma (6.0.1) lib/puma/request.rb:93:in `block in handle_request'
[06610406-6809-49ca-93b5-170a9f816418] puma (6.0.1) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
[06610406-6809-49ca-93b5-170a9f816418] puma (6.0.1) lib/puma/request.rb:92:in `handle_request'
[06610406-6809-49ca-93b5-170a9f816418] puma (6.0.1) lib/puma/server.rb:429:in `process_client'
[06610406-6809-49ca-93b5-170a9f816418] puma (6.0.1) lib/puma/server.rb:232:in `block in run'
[06610406-6809-49ca-93b5-170a9f816418] puma (6.0.1) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

```

**Comment by Kumar-Gowda-D** [comment]
@asadakbar could you please assign this work for me i will complete as soon as possible
