### ISSUE TITLE
Add support for has_and_belongs_to_many

### ISSUE THREAD

**Issue by silva96** [motor-admin/motor-admin#20]
Hey! I have a has_and_belongs_to_many relation and it's failing to load resources in the joined table

```
 NotImplementedError (NotImplementedError):
12:44:38 web.1    |
12:44:38 web.1    | activerecord (6.1.4.1) lib/active_record/reflection.rb:560:in `association_class'
12:44:38 web.1    | activerecord (6.1.4.1) lib/active_record/associations.rb:315:in `association'
12:44:38 web.1    | activerecord (6.1.4.1) lib/active_record/associations/builder/association.rb:103:in `posts'
12:44:38 web.1    | cancancan (3.3.0) lib/cancan/controller_resource_loader.rb:71:in `resource_base_through_parent_resource'
12:44:38 web.1    | cancancan (3.3.0) lib/cancan/controller_resource_loader.rb:77:in `resource_base_through'
12:44:38 web.1    | cancancan (3.3.0) lib/cancan/controller_resource_loader.rb:91:in `resource_base'
12:44:38 web.1    | cancancan (3.3.0) lib/cancan/controller_resource.rb:78:in `load_collection?'
12:44:38 web.1    | cancancan (3.3.0) lib/cancan/controller_resource_loader.rb:19:in `load_resource'
12:44:38 web.1    | cancancan (3.3.0) lib/cancan/controller_resource.rb:33:in `load_and_authorize_resource'
12:44:38 web.1    | motor-admin (0.2.24) app/controllers/concerns/motor/load_and_authorize_dynamic_resource.rb:62:i
```

**Comment by omohokcoj** [comment]
@silva96 thanks for reporting this, is has been fixed in the newest ruby gem release.

**Comment by silva96** [comment]
Great as usual. Thanks a lot!
