### ISSUE TITLE
getting Error: "We're sorry, but something went wrong"

### ISSUE THREAD

**Issue by ilovefreesw** [motor-admin/motor-admin#26]
After installing it from the Ubuntu binary, the following screen appears.

![image](https://user-images.githubusercontent.com/77317006/145536791-99896a64-062a-4f73-88ab-50c62cf3b890.png)

Same thing happens on Heroku.

![image](https://user-images.githubusercontent.com/77317006/145536967-514a2239-32f4-43ac-9b99-1dc5af8c46c5.png)

I am using online PostgreSQL server on my PC which is running Kubuntu 20.04. After I add database, this error shows up. Here are logs I see on my terminal.

```
⚡ Motor::Admin is starting under /

Puma starting in single mode...
* Puma version: 5.5.2 (ruby 2.7.1-p83) ("Zawgyi")
*  Min threads: 20
*  Max threads: 20
*  Environment: production
*          PID: 3602
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
I, [2021-12-10T13:13:52.362012 #3602]  INFO -- : [7f72711d-ce73-4776-bdff-f179fe974b26] {"method":"GET","path":"/sign_in","status":302,"duration":6.77,"view":0.0,"db":1.46,"fwd":"127.0.0.1","uid":null}
I, [2021-12-10T13:13:52.377372 #3602]  INFO -- : [a8cadbc9-4aba-4775-8379-0e9dbe699383] {"method":"GET","path":"/setup","status":200,"duration":9.53,"view":4.01,"db":0.57,"fwd":"127.0.0.1","uid":null}
I, [2021-12-10T13:14:19.213741 #3602]  INFO -- : [1c3883b5-3adf-4d11-91cf-94a7433ec6e2] {"method":"POST","path":"/api/setup","status":200,"duration":979.41,"view":0.22,"db":643.52,"fwd":"127.0.0.1","uid":1}
I, [2021-12-10T13:15:18.011325 #3602]  INFO -- : [09ec0c90-4efc-4cc7-ab38-ab7f6f53869a] {"method":"POST","path":"/api/verify_db_connection","status":200,"duration":1656.82,"view":0.0,"db":1.13,"fwd":"127.0.0.1","uid":1}
I, [2021-12-10T13:15:18.163022 #3602]  INFO -- : [f23e1a68-c04c-4748-9ea8-8dc97701cc8a] {"method":"POST","path":"/api/encrypted_configs","status":200,"duration":139.68,"view":0.64,"db":130.77,"fwd":"127.0.0.1","uid":1}
I, [2021-12-10T13:15:25.461007 #3602]  INFO -- : [68ca1ddb-c3db-4d7a-87f3-fa8113296149] {"method":"GET","path":"/","status":500,"duration":5696.31,"view":0.0,"db":3614.06,"fwd":"127.0.0.1","uid":1}
F, [2021-12-10T13:15:25.461997 #3602] FATAL -- : [68ca1ddb-c3db-4d7a-87f3-fa8113296149]   
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] NameError (wrong constant name Product theme):
[68ca1ddb-c3db-4d7a-87f3-fa8113296149]   
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] lib/motor/define_ar_models.rb:96:in `const_set'
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] lib/motor/define_ar_models.rb:96:in `block in define_models'
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] lib/motor/define_ar_models.rb:77:in `each'
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] lib/motor/define_ar_models.rb:77:in `filter_map'
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] lib/motor/define_ar_models.rb:77:in `define_models'
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] lib/motor/define_ar_models.rb:53:in `block in call'
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] lib/motor/define_ar_models.rb:50:in `synchronize'
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] lib/motor/define_ar_models.rb:50:in `call'
[68ca1ddb-c3db-4d7a-87f3-fa8113296149] config/initializers/set_db_connection_and_define_ar_models.rb:28:in `set_db_connection_and_define_ar_models'
```

**Comment by omohokcoj** [comment]
Hi @ilovefreesw thanks for reporting this issue.
Looks like it's caused by ProductTheme table name - can you provide the exact name of the table in your database - it could help to resolve the issue quickly.

**Comment by ilovefreesw** [comment]
It is "Product Themes"

![image](https://user-images.githubusercontent.com/77317006/145546685-242a2ad4-845f-42a1-8960-ba350e9fbe0d.png)

**Comment by omohokcoj** [comment]
@ilovefreesw spaces in table names are not supported in the latest version - to make everything work you might need to rename your table to product_themes.
I will add a fix for spaces in the new release next week - will let you know when it's ready in case you need keep the original names with spaces.

**Comment by ilovefreesw** [comment]
> @ilovefreesw spaces in table names are not supported in the latest version - to make everything work you might need to rename your table to product_themes. I will add a fix for spaces in the new release next week - will let you know when it's ready in case you need keep the original names with spaces.

Well it is just a test database that I exported from Airtable and I didn't notice the name table name. I know spaces in table names is not a good practice but ig software shouldn't crash for this. Anyway...i just though reporting it would be good. Thank anyway :)
