### ISSUE TITLE
Unable to send email alerts

### ISSUE THREAD

**Issue by ankurgoels** [motor-admin/motor-admin#94]
I have added mailtrap to SMTP credentials but when I click send now button on the alerts page I get the error, 'SSL_CTX_load_verify_file: system lib'. How to fix this?

Below is the docker-compose.yml

```
version: '3'

services:
  app:
    image: 'motoradmin/motoradmin:latest'
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - '.:/app'
    environment:
      SECRET_KEY_BASE: <64 Character KEY>
      DATABASE_URL:
```

Log Data
```
app-1  | E, [2023-04-17T13:04:09.317221 #1] ERROR -- : [8fe437ae-fbd0-4e84-8250-1950b7dff436] SSL_CTX_load_verify_file: system lib
app-1  | E, [2023-04-17T13:04:09.317726 #1] ERROR -- : [8fe437ae-fbd0-4e84-8250-1950b7dff436] /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:681:in `initialize'
app-1  | /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:681:in `new'
app-1  | /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:681:in `ssl_socket'
app-1  | /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:686:in `tlsconnect'
app-1  | /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:666:in `do_start'
app-1  | /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:611:in `start'
app-1  | /usr/local/bundle/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
app-1  | /usr/local/bundle/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
app-1  | /usr/local/bundle/gems/mail-2.8.1/lib/mail/message.rb:269:in `deliver!'
app-1  | /usr/local/bundle/gems/actionmailer-7.0.4.3/lib/action_mailer/message_delivery.rb:109:in `block in deliver_now!'
app-1  | /usr/local/bundle/gems/actionmailer-7.0.4.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
app-1  | /usr/local/bundle/gems/actionmailer-7.0.4.3/lib/action_mailer/message_delivery.rb:108:in `deliver_now!'
app-1  | /opt/motor-admin/vendor/motor-admin/lib/motor/alerts.rb:18:in `block in send_email_alert'
app-1  | /opt/motor-admin/vendor/motor-admin/lib/motor/alerts.rb:16:in `each'
app-1  | /opt/motor-admin/vendor/motor-admin/lib/motor/alerts.rb:16:in `send_email_alert'
app-1  | /opt/motor-admin/vendor/motor-admin/lib/motor/alerts.rb:11:in `send_alert'
app-1  | /opt/motor-admin/vendor/motor-admin/app/controllers/motor/send_alerts_controller.rb:11:in `create'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/base.rb:215:in `process_action'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/rendering.rb:53:in `process_action'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
app-1  | /usr/local/bundle/gems/audited-5.3.2/lib/audited/sweeper.rb:16:in `around'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
app-1  | /usr/local/bundle/gems/audited-5.3.2/lib/audited/sweeper.rb:16:in `around'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/callbacks.rb:233:in `process_action'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `block in instrument'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `instrument'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
app-1  | /usr/local/bundle/gems/activerecord-7.0.4.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/abstract_controller/base.rb:151:in `process'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal.rb:188:in `dispatch'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_controller/metal.rb:251:in `dispatch'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:32:in `serve'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `each'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `serve'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
app-1  | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/engine.rb:530:in `call'
app-1  | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/railtie.rb:226:in `public_send'
app-1  | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/railtie.rb:226:in `method_missing'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:50:in `block in serve'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `each'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/journey/router.rb:32:in `serve'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:852:in `call'
app-1  | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
app-1  | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
app-1  | /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
app-1  | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
app-1  | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/etag.rb:27:in `call'
app-1  | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/conditional_get.rb:40:in `call'
app-1  | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/head.rb:12:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
app-1  | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:266:in `context'
app-1  | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/session/abstract/id.rb:260:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/cookies.rb:704:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:99:in `run_callbacks'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
app-1  | /usr/local/bundle/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
app-1  | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/rack/logger.rb:25:in `block in call'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:37:in `tagged'
app-1  | /usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `tagged'
app-1  | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/rack/logger.rb:25:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
app-1  | /usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
app-1  | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/method_override.rb:24:in `call'
app-1  | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/runtime.rb:22:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/static.rb:23:in `call'
app-1  | /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/sendfile.rb:110:in `call'
app-1  | /usr/local/bundle/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
app-1  | /usr/local/bundle/gems/railties-7.0.4.3/lib/rails/engine.rb:530:in `call'
app-1  | /usr/local/bundle/gems/puma-6.0.1/lib/puma/configuration.rb:268:in `call'
app-1  | /usr/local/bundle/gems/puma-6.0.1/lib/puma/request.rb:93:in `block in handle_request'
app-1  | /usr/local/bundle/gems/puma-6.0.1/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
app-1  | /usr/local/bundle/gems/puma-6.0.1/lib/puma/request.rb:92:in `handle_request'
app-1  | /usr/local/bundle/gems/puma-6.0.1/lib/puma/server.rb:429:in `process_client'
app-1  | /usr/local/bundle/gems/puma-6.0.1/lib/puma/server.rb:232:in `block in run'
app-1  | /usr/local/bundle/gems/puma-6.0.1/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
app-1  | I, [2023-04-17T13:04:09.320162 #1]  INFO -- : [8fe437ae-fbd0-4e84-8250-1950b7dff436] {"method":"POST","path":"/api/send_alerts","status":500,"duration":820.59,"view":1.26,"db":35.78,"fwd":"182.72.252.34","uid":1}
```

**Comment by omohokcoj** [comment]
@ankurgoels thanks for reporting this bug - it has been fixed in the latest 0.4.12 docker image
